shop/core/urls.py
from django.contrib import admin
from django.urls import path, include

from shop_app.views import RegisterFormView, UserProfileView, UpdateProfileView, PasswordsChangeView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop_app.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/register/", RegisterFormView.as_view(), name="register"),
    path("accounts/profile/<int:pk>/", UserProfileView.as_view(), name="profile"),
    path("accounts/update_profile/", UpdateProfileView.as_view(), name="update_profile"),
    path("accounts/password", PasswordsChangeView.as_view(template_name='registration/change_password.html'),
         name='change_password'),

]

shop/shop_app/urls.py
from django.urls import path
from . import views
from .views import add_to_cart


urlpatterns = [
    path('', views.HomeShopView.as_view(), name='home'),
    path('shop/<int:pk>/book', views.BookDetailView.as_view(), name='book-detail'),
    path('add/', add_to_cart, name='add_to_cart'),
    ]

shop/shop_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse



class Book(models.Model):
    title = models.CharField(max_length=120)
    author = models.CharField(max_length=120)
    summary = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    publication_year = models.DateTimeField(blank=True, null=True)
    # id_in_warehouse = models.ForeignKey(WarehouseBook, on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.pk)])

    def __str__(self):
        return self.title



class Order(models.Model):
    STATUS_CHOICE = (
        ('cart', 'Cart'),
        ('ordered', 'Ordered'),
        ('success','Success'),
        ('Fail', 'fail'),
    )

    user_id = models.ForeignKey(User,on_delete=models.CASCADE)
    status = models.CharField(choices=STATUS_CHOICE, max_length=10)
    delivery_adress = models.CharField(max_length=320)
    created_at = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=100, decimal_places=2)

class OrderItem(models.Model):
    order_id = models.ForeignKey(Order, on_delete=models.CASCADE)
    book_id = models.OneToOneField(Book, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

shop/shop_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import TextInput
from shop_app.models import Order

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}), required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        widgets = {
            'username': TextInput(attrs={'placeholder': 'Username',
                                         'style': 'width: 300px;',
                                         'class': 'form-control'
                                         }),
                    }



class OrderForm(forms.ModelForm):
    pass

class AddToCartForm(forms.Form):
    book_id = forms.IntegerField(widget=forms.HiddenInput())

shop/shop_app/views.py
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect

from django.views import generic
from django.urls import reverse_lazy

from shop_app.models import Book, Order, OrderItem
from shop_app.forms import RegisterForm, AddToCartForm



User = get_user_model()

class HomeShopView(generic.ListView):
    model = Book
    # paginate_by = 3
    template_name = 'home.html'

class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        user = form.save()
        user = authenticate(username=user.username, password=form.cleaned_data.get('password1'))
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UserProfileView(generic.DetailView):
    model = User
    template_name = 'registration/profile.html'


class UpdateProfileView(LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = 'registration/update_profile.html'
    fields = ['username', 'email']
    success_url = reverse_lazy('home')
    success_message = "Profile success update"

    def get_object(self, queryset=None):
        user = self.request.user
        return


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('home')


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'shop/book_detail.html'

def add_to_cart(request):
    if request.method == 'POST':
        form = AddToCartForm(request.POST)
        if form.is_valid():
            book_id = form.cleaned_data['book_id']
            book = Book.objects.get(id=book_id)
            user = request.user
            order, created = Order.objects.get_or_create(user_id=user, status='cart')
            order_item, created = OrderItem.objects.get_or_create(order_id=order, book_id=book)
            order_item.quantity += 1
            order_item.save()
            return redirect('cart_shop')
    else:
        form = AddToCartForm()
    return render(request, 'shop/add_to_cart.html', {'form': form})

shop/shop_app/templates/base.html
<!doctype html>
<!--{% load static %}-->
<link rel="stylesheet" href="{% static 'blog/style.css' %}">
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Book{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
  <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
          height="15"
          alt="MDB Logo"
          loading="lazy"
        />
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Team</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Projects</a>-->
<!--        </li>-->
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->

    <div class="d-flex align-items-center">
        <!-- Icon -->

             <a type="button" class="btn btn-outline-danger" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"></path>
                </svg>
                        Cart
             </a>
            <a type="button" class="btn btn-link px-3 me-2"  href="{% url 'home' %}">
              Logout
            </a>

            <a type="button" class="btn btn-link px-3 me-2"  href="{% url 'login' %}">
              Login
            </a>
            <a type="button"  class="btn btn-primary me-3" href="{% url 'register' %}">
              Registration
            </a>



      <!-- Notifications -->
      <div class="dropdown">
        <a
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>

        </a>

      </div>

    <!-- Right elements -->
        </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->
<!--       <ul class="navbar-nav ml-auto">-->
<!--            <li class="nav-item">-->
<!--&lt;!&ndash;               {% if user.is_authenticated %}&ndash;&gt;-->
<!--                  <li class="nav-item">-->
<!--                  <a class="nav-link" href= "{% url 'profile' user.id%}">{{request.user.username}}</a>-->
<!--                  </li>-->
<!--&lt;!&ndash;               {% endif %}&ndash;&gt;-->
<!--            </li>-->
<!--        </ul>-->
<!--</nav>-->
<div class="container">
    {% block content %}

    {% endblock %}
    {% block pagination %}
        {% if is_paginated %}
            <nav aria-label="pagination-blog">
                <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="{{ request.path }}?page=1">first</a></li>
                        <li class="page-item"><a class="page-link"  href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a></li>
                        {% endif %}
                      {% if page_obj.has_next %}
                        <li class="page-item"><a class="page-link"  href="{{ request.path }}?page={{  page_obj.next_page_number }}">next</a></li>
                        <li class="page-item"><a  class="page-link"  href="{{ request.path }}?page={{  page_obj.paginator.num_pages }}">last</a></li>
                      {% endif %}

                </ul>
            </nav>
        {% endif %}
    {% endblock %}
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>-->
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
      integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
      crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
      integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
      crossorigin="anonymous"></script>
<!--<script src="{% static 'js/contact.js' %}"></script>-->

<!--  <div class="modal fade" id="contact_us" aria-hidden="true" >-->
<!--    <div class="modal-dialog">-->
<!--        <div class="modal-content">-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

  </body>
</html>

shop/shop_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
<h1>Book</h1>
{% if book_list %}
  <ul>
    {% for book in book_list %}
    <li>
      <a href="{{ book.get_absolute_url }}">{{book.title}}</a>
    </li>
    {% endfor %}
  </ul>
{% else %}
    Book will be added soon
{% endif %}
  <button type="button" class="btn btn-primary">Buy</button>
{% endblock %}

shop/shop_app/templates/shop/add_to_cart.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Add to Cart</button>
</form>
{% endblock %}

shop/shop_app/templates/shop/book_detail.html
{% extends 'base.html' %}


<title>{% block title %}{{book.title}}{% endblock %}</title>

{% block content %}
  <h1>{{book.title}}</h1>
  <br/><br/>

  <p>{{book.author}}</p>
  <p>{{book.publication_year}}</p>
  <p>{{book.summary}}</p>

  <br/><br/>

  <p>{{book.price}}</p>
  <a type="button" class="btn btn-primary" href="{% url 'add_to_cart' %}">Buy</a>


{% endblock %}

shop/shop_app/templates/shop/cart_shop.html
{% extends 'base.html' %}

{% block content %}


{% endblock %}